name: 'Deploy to GitHub Pages'
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn docz:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.8
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .docz/dist
