name: Release
on:
  push:
    branches:
      - master
    paths:
      - 'packages/konstellation-web-components/**'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install
        run: yarn install
      - name: Build
        working-directory: ./packages/konstellation-web-components
        run: yarn build
      - name: Release
        working-directory: ./packages/konstellation-web-components
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
